library(knitr)
library(rvest)
library(gsubfn)
library(tidyr)
library(tmap)
library(shiny)
library(readr)
library(dplyr)
library(tidyverse)
library(gridExtra)

source("lib/uvozi.zemljevid.r", encoding="UTF-8")
